import os
import pymysql
from dotenv import load_dotenv

load_dotenv()

# Gunakan URL dari .env jika ada, atau default local
db_url = os.getenv('DW_DATABASE_URL', 'mysql+pymysql://root:@localhost/dw_hospitality')

# Parse parameter koneksi dari URL
# Format: mysql+pymysql://user:pass@host:port/dbname
try:
    # Hapus prefix mysql+pymysql://
    clean_url = db_url.replace("mysql+pymysql://", "")
    # Pisahkan user:pass dan host:port/dbname
    user_pass, host_port_db = clean_url.split("@")
    
    if ":" in user_pass:
        user, password = user_pass.split(":")
    else:
        user = user_pass
        password = ""
        
    host_port, dbname = host_port_db.split("/")
    if ":" in host_port:
        host, port = host_port.split(":")
        port = int(port)
    else:
        host = host_port
        port = 3306
except Exception:
    # Fallback default
    user = "root"
    password = ""
    host = "localhost"
    port = 3306
    dbname = "dw_hospitality"

print(f"Connecting to database: {dbname} on {host}:{port} as {user}...")

try:
    conn = pymysql.connect(
        host=host,
        port=port,
        user=user,
        password=password,
        database=dbname,
        charset='utf8mb4',
        cursorclass=pymysql.cursors.DictCursor
    )
except Exception as e:
    print(f"Error connecting to local MySQL: {e}")
    print("Pastikan XAMPP/Laragon/MySQL local Anda sedang berjalan.")
    exit(1)

tables = [
    'dim_time',
    'dim_guest',
    'dim_hotel',
    'dim_room',
    'dim_booking_channel',
    'fact_reservation'
]

output_file = 'backup_dw.sql'
print(f"Dumping database to {output_file}...")

with open(output_file, 'w', encoding='utf-8') as f:
    f.write("-- Database dump generated by Python script\n")
    f.write("SET FOREIGN_KEY_CHECKS = 0;\n\n")
    
    with conn.cursor() as cursor:
        for table in tables:
            print(f"Dumping table: {table}...")
            # Get Create Table
            try:
                cursor.execute(f"SHOW CREATE TABLE `{table}`")
                create_stmt = cursor.fetchone()
                create_sql = create_stmt['Create Table']
                f.write(f"DROP TABLE IF EXISTS `{table}`;\n")
                f.write(f"{create_sql};\n\n")
            except Exception as e:
                print(f"Warning: Could not get schema for {table}: {e}")
                continue
            
            # Get Data
            cursor.execute(f"SELECT * FROM `{table}`")
            rows = cursor.fetchall()
            if not rows:
                continue
                
            # Generate INSERTS
            columns = rows[0].keys()
            col_list = ", ".join([f"`{col}`" for col in columns])
            
            f.write(f"LOCK TABLES `{table}` WRITE;\n")
            # Write in chunks of 500 rows to prevent huge single queries
            chunk_size = 500
            for i in range(0, len(rows), chunk_size):
                chunk = rows[i:i+chunk_size]
                vals = []
                for row in chunk:
                    row_vals = []
                    for col in columns:
                        val = row[col]
                        if val is None:
                            row_vals.append("NULL")
                        elif isinstance(val, (int, float)):
                            row_vals.append(str(val))
                        else:
                            # Escape string values
                            escaped = conn.escape(str(val))
                            row_vals.append(escaped)
                    vals.append(f"({', '.join(row_vals)})")
                
                f.write(f"INSERT INTO `{table}` ({col_list}) VALUES \n" + ",\n".join(vals) + ";\n")
            
            f.write(f"UNLOCK TABLES;\n\n")
            
    f.write("SET FOREIGN_KEY_CHECKS = 1;\n")

print(f"Successfully exported {len(tables)} tables to {output_file}!")
conn.close()
